
export const config = {
  CLOUDINARY_NAME: process.env.REACT_APP_CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_MAX_FILE_SIZE: process.env.REACT_APP_CLOUDINARY_MAX_FILE_SIZE,
  CLOUDINARY_PREFIX: process.env.REACT_APP_CLOUDINARY_PREFIX,
};
